name: firebase_picture_uploader
description: Picture upload widget which helps selecting and uploading one or multiple images to firebase storage.
version: 1.3.2
homepage: https://github.com/Rodiii/flutter_firebase_picture_uploader
maintainer: Christoph Rothermel (@rothech)

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
    
  cached_network_image: ^3.2.3
  firebase_storage: ^12.1.3
  firebase_core: ^3.3.0
  image: ^4.2.0 
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  shared_preferences: ^2.3.1
  path_provider: ^2.1.4
  cupertino_icons:


dev_dependencies:
  flutter_test:
    sdk: flutter
 
